// File generated by FlutterFire CLI based on google-services.json.
// Project: ailaga-d77b8
// Package: com.ailaga.ailaga
//
// DO NOT EDIT — regenerate with:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=ailaga-d77b8
//
// SECURITY NOTE: The API key below is the Firebase Android API key. It is safe
// to include in source control for a mobile app — Firebase enforces security
// through SHA-1/SHA-256 certificate fingerprint restrictions configured in the
// Firebase console, NOT by keeping the key secret.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'AILaga does not support web. '
        'Configure a web app in the Firebase console if needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not yet configured. Add GoogleService-Info.plist '
          'and run flutterfire configure to generate iOS options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Android configuration derived from android/app/google-services.json.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_L04YYEJGXk-6mYgWYeR2JcJPhw7J870',
    appId: '1:884019261468:android:f5383acd6195c559fe6fd9',
    messagingSenderId: '884019261468',
    projectId: 'ailaga-d77b8',
    storageBucket: 'ailaga-d77b8.firebasestorage.app',
  );
}
