import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

import '../../features/medications/domain/medication_entity.dart';
import '../../features/measurements/domain/measurement_entity.dart';
import '../../features/appointments/domain/appointment_entity.dart';
import '../../features/care_notes/domain/care_note_entity.dart';

class PdfGenerator {
  Future<Uint8List> generate({
    required String recipientName,
    required DateTime periodStart,
    required DateTime periodEnd,
    required List<MedicationOccurrenceEntity> occurrences,
    required List<MeasurementEntity> measurements,
    required List<AppointmentEntity> appointments,
    required List<CareNoteEntity> notes,
  }) async {
    final pdf = pw.Document();

    final dateFormatter = DateFormat('MMMM d, yyyy');
    final timeFormatter = DateFormat('h:mm a');
    final generatedAt = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('AILaga Care Report',
                  style: pw.TextStyle(
                      fontSize: 24, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.Text('Care Recipient: $recipientName',
                  style: const pw.TextStyle(fontSize: 16)),
              pw.Text(
                  'Period: ${dateFormatter.format(periodStart)} to ${dateFormatter.format(periodEnd)}'),
              pw.Text(
                  'Generated: ${dateFormatter.format(generatedAt)} ${timeFormatter.format(generatedAt)}'),
              pw.Divider(),
              pw.SizedBox(height: 16),
            ],
          );
        },
        footer: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Divider(),
              pw.Text(
                'Generated by AILaga. This is not a medical diagnosis.',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
            ],
          );
        },
        build: (context) {
          return [
            if (measurements.isNotEmpty)
              _buildMeasurementsSection(
                  measurements, dateFormatter, timeFormatter),
            if (occurrences.isNotEmpty)
              _buildMedicationsSection(
                  occurrences, dateFormatter, timeFormatter),
            if (appointments.isNotEmpty)
              _buildAppointmentsSection(
                  appointments, dateFormatter, timeFormatter),
            if (notes.isNotEmpty)
              _buildNotesSection(notes, dateFormatter, timeFormatter),
          ];
        },
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildSectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 16, bottom: 8),
      child: pw.Text(
        title,
        style: pw.TextStyle(
            fontSize: 18,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.teal800),
      ),
    );
  }

  pw.Widget _buildMeasurementsSection(
      List<MeasurementEntity> items, DateFormat d, DateFormat t) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Measurements'),
        pw.TableHelper.fromTextArray(
          headers: ['Type', 'Value', 'Unit', 'Timestamp', 'Source'],
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
          cellAlignment: pw.Alignment.centerLeft,
          data: items
              .map((m) => [
                    m.measurementType.name,
                    m.value1.toString(),
                    m.unit,
                    '${d.format(m.measuredAt)} ${t.format(m.measuredAt)}',
                    m.sourceType,
                  ])
              .toList(),
        ),
      ],
    );
  }

  pw.Widget _buildMedicationsSection(
      List<MedicationOccurrenceEntity> items, DateFormat d, DateFormat t) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Medication History'),
        pw.TableHelper.fromTextArray(
          headers: ['Medication', 'Scheduled', 'Status', 'Status Time'],
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
          cellAlignment: pw.Alignment.centerLeft,
          data: items.map((m) {
            // Wait, we don't have medication name in Occurrence entity.
            // In a real app we'd join with the schedule, but we'll use scheduleId as a fallback for now.
            final medName = m.medicationScheduleId;
            final scheduled =
                '${d.format(m.scheduledAt)} ${t.format(m.scheduledAt)}';
            final statusTime = m.statusUpdatedAt != null
                ? '${d.format(m.statusUpdatedAt!)} ${t.format(m.statusUpdatedAt!)}'
                : '';
            return [
              medName,
              scheduled,
              m.status.name,
              statusTime,
            ];
          }).toList(),
        ),
      ],
    );
  }

  pw.Widget _buildAppointmentsSection(
      List<AppointmentEntity> items, DateFormat d, DateFormat t) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Appointments'),
        pw.TableHelper.fromTextArray(
          headers: ['Date', 'Provider/Facility', 'Purpose', 'Status'],
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
          cellAlignment: pw.Alignment.centerLeft,
          data: items
              .map((a) => [
                    '${d.format(a.scheduledAt)} ${t.format(a.scheduledAt)}',
                    a.providerOrFacility ?? '',
                    a.purpose ?? '',
                    a.status,
                  ])
              .toList(),
        ),
      ],
    );
  }

  pw.Widget _buildNotesSection(
      List<CareNoteEntity> items, DateFormat d, DateFormat t) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Care Notes (Selected)'),
        ...items.map((n) {
          return pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 8),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('${d.format(n.observedAt)} ${t.format(n.observedAt)}',
                    style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold, fontSize: 10)),
                pw.Text(n.originalText),
              ],
            ),
          );
        }),
      ],
    );
  }
}
